---

Parameters:
  AvailabilityZone:
    Type: String
    Default: us-east-1c

Resources:

  TestDBCluster:
    Type: AWS::DocDB::DBCluster
    Properties:
      AvailabilityZones:
        - !Ref AvailabilityZone
      MasterUsername: testadmin
      MasterUserPassword: test1234
      DBClusterIdentifier: docdb-test-cluster
      StorageEncrypted: true
      BackupRetentionPeriod: 1 # We only store backup for one day
      Port: 27017
      DeletionProtection: false

  TestDBInstance:
    Type: AWS::DocDB::DBInstance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      DBInstanceIdentifier: docdb-test-instance
      DBClusterIdentifier: !Ref TestDBCluster
      DBInstanceClass: db.t4g.medium
